Using cpu device
tot num of params: 623067
[2024-02-17 15:29:53,524][absl][WARNING] - Cannot set velocity on Entity with no free joint.
Logging to /Users/sangbin/maze/outputs/2024-02-17/15-29-46/wandb/run-20240217_152950-a5xqzxpo/files/a5xqzxpo/PPO_1
step 1
step 2
step 3
step 4
step 5
step 6
step 7
step 8
step 9
step 10
step 11
Traceback (most recent call last):
  File "/Users/sangbin/maze/train_epn_3d.py", line 92, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 119, in run
    ret = run_job(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/Users/sangbin/maze/train_epn_3d.py", line 79, in main
    model.learn(total_timesteps=cfg.optim.total_timesteps, callback=callback)
  File "/Users/sangbin/maze/ppo/epn/epn.py", line 464, in learn
    continue_training = self.collect_rollouts(
  File "/Users/sangbin/maze/ppo/epn/epn.py", line 212, in collect_rollouts
    actions, values, log_probs = self.policy.forward(
  File "/Users/sangbin/maze/ppo/epn/policies.py", line 158, in forward
    combined_embedding = self.model(memory, obs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/sangbin/maze/ppo/epn/model.py", line 90, in forward
    new_prev_states = self.image_embedding_conv(memory_prev_image[i])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
KeyboardInterrupt
Exception ignored in atexit callback: <function ContextBase.__init__.<locals>._free_at_exit at 0x349eb3520>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/base.py", line 59, in _free_at_exit
    self_weakref()._free_unconditionally()  # pylint: disable=protected-access
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
    self._render_executor.terminate(self._free_on_executor_thread)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/executor/render_executor.py", line 144, in terminate
    cleanup_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/base.py", line 107, in _free_on_executor_thread
    self._platform_free()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dm_control/_render/glfw_renderer.py", line 67, in _platform_free
    self._destroy_window(self._context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glfw/__init__.py", line 1278, in destroy_window
    _glfw.glfwDestroyWindow(window)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/glfw/__init__.py", line 686, in errcheck
    def errcheck(result, *args):
KeyboardInterrupt: